---
# tasks file for wso2_start_setup
#


###################################################################################################
############################## Start Products ######################################################
#
##########################################
#
#

- name: Create tmp file
  lineinfile: path="{{ PRODUCT_HOME }}/password-tmp" create=yes line="{{ KEY_PASS }}"
  when:
    - PRODUCT_NAME != "msg-broker"

- name: Create tmp file
  lineinfile: path="{{ PRODUCT_HOME }}/wso2/broker/password-tmp" create=yes line="{{ KEY_PASS }}"
  when:
    - PRODUCT_NAME == "msg-broker"

#########################################

- name: Start wso2 product INTEGRATOR/ESB
  shell: "{{ PRODUCT_HOME }}/bin/integrator.sh start -Desb.config.dss.url={{ DSS_URL }} -Desb.loadbalancer.url={{ LOAD_BALANCER_URL }} -DAndesAckWaitTimeOut=1800000 -Desb.cluster.institutions={{INSTITUTIONS | default('')}} -Denv={{ENV}} -Dsetup"
  when:
    - PRODUCT_FLAG == "integrator"
    - PRODUCT_NAME == "esb"


########################################

- name: Start wso2 product INTEGRATOR/DSS
  shell: "{{ PRODUCT_HOME }}/bin/integrator.sh start -Dsetup"
  when:
    - PRODUCT_FLAG == "integrator"
    - PRODUCT_NAME == "dss"

########################################

- name: Start wso2 product INTEGRATOR/MSG-BROKER
  shell: "{{ PRODUCT_HOME }}/wso2/broker/bin/wso2server.sh start -Dsetup"
  when:
    - PRODUCT_FLAG == "integrator"
    - PRODUCT_NAME == "msg-broker"


- name: Wait Broker Start to Start the next 
  wait_for:
    host: "{{inventory_hostname}}"
    port: 9446
    delay: 40
    state: drained
  when:
    - PRODUCT_FLAG == "integrator"
    - PRODUCT_NAME == "msg-broker"
    - CLUSTER == "true"


########################################

- name: Start wso2 product API-MGR
  shell: "{{ PRODUCT_HOME }}/bin/wso2server.sh start -Dsetup -Datgeserviceurl={{ATGE_SERVICE_URL}} -Ddkcserviceurl={{DKC_SERVICE_URL| default('')}} " 
  when:
    - PRODUCT_FLAG == "api-mgr"



###############################################

- name: Wait Instance to Start before start the next
  wait_for:
    host: "{{inventory_hostname}}"
    port: 9443
    delay: 40
    state: drained
  when:
    - PRODUCT_NAME != "msg-broker"
