---
# tasks file for wso2_install
- block:

  - name: Creates install directory
    file: path="{{ wso2_install_path }}/{{ wso2_product_name }}" mode=775 recurse=yes state=directory

# Uncompressing WSO2 zip
  
  - name: Uncompressing WSO2 zip file
    unarchive: 
      src="{{ wso2_zip_file_location }}" 
      dest="{{ wso2_install_path }}/{{ wso2_product_name }}" 
      copy=yes

# Setting permissions to WSO2 scripts
 
  - name: Setting permissions to WSO2 scripts  
    file:
      path="{{ wso2_install_path }}/{{ wso2_product_name }}/bin/"
      mode=775
      recurse=yes
      state=directory
    when: PRODUCT_NAME != "msg-broker"

  - name: Setting permissions to WSO2 scripts  
    file:
      path="{{ wso2_install_path }}/{{ wso2_product_name }}/wso2/broker/bin/"
      mode=775
      recurse=yes
      state=directory
    when: PRODUCT_NAME == "msg-broker"



  become_user: "{{ user }}"    
  
      
 
