---
# tasks file for wso2_setup

################### API-MGR ####################

- name: Copy MySQL connector files
  copy: src="{{ role_path }}/files/mysql-connector-java-5.1.41-bin.jar" dest="{{ PRODUCT_HOME }}/repository/components/lib/"
  become_user: "{{ user }}"
  when: PRODUCT_FLAG == "api-mgr"

- name: Edit repository/conf/datasources/master-datasources.xml
  template:
    src: "{{ role_path }}/templates/{{ PRODUCT_FLAG }}/master-datasources.xml.j2"
    dest: "{{ PRODUCT_HOME }}/repository/conf/datasources/master-datasources.xml"
    mode: 0775
  with_items:
    - { db_name: "{{ REG_DB_NAME }}", url: "{{ REG_DB_URL }}", driver: "{{ DB_DRIVER }}", user: "{{ REG_DB_USER}}", pass: "{{ REG_DB_PASS }}" }
  become_user: "{{ user }}"
  when: PRODUCT_FLAG == "api-mgr"

- name: Edit conf files
  template:
     src: "{{ role_path }}/templates/{{ PRODUCT_FLAG }}/{{ item.src }}"
     dest: "{{ PRODUCT_HOME }}/repository/conf/{{ item.dest }}"
     mode: 0775
  with_items:
    - { src: registry.xml.j2, dest: registry.xml }
    - { src: user-mgt.xml.j2, dest: user-mgt.xml }
    - { src: identity.xml.j2, dest: identity/identity.xml }
    - { src: EndpointConfig.properties.j2, dest: identity/EndpointConfig.properties }
    - { src: application-authentication.xml.j2, dest: identity/application-authentication.xml }
    - { src: broker.xml.j2, dest: broker.xml }
    - { src: catalina-server.xml.j2, dest: tomcat/catalina-server.xml }
    - { src: tomcat-users.xml.j2, dest: tomcat/tomcat-users.xml }
    - { src: data-bridge-config.xml.j2, dest: data-bridge/data-bridge-config.xml }
    - { src: axis2.xml.j2,dest: axis2/axis2.xml }
    - { src: carbon.xml.j2, dest: carbon.xml }
  become_user: "{{ user }}"
  when: PRODUCT_FLAG == "api-mgr"

#################### INTEGRATOR ###################

- name: Copy MySQL connector files
  copy: src="{{ role_path }}/files/mysql-connector-java-5.1.41-bin.jar" dest="{{ PRODUCT_HOME }}/lib/"
  become_user: "{{ user }}"
  when: PRODUCT_FLAG == "integrator"

- name: Edit conf/datasources/master-datasources.xml
  template:
    src: "{{ role_path }}/templates/{{ PRODUCT_FLAG }}/master-datasources.xml.j2"
    dest: "{{ PRODUCT_HOME }}/conf/datasources/master-datasources.xml"
    mode: 0775
  with_items:
    - { db_name: "{{ REG_DB_NAME }}", url: "{{ REG_DB_URL }}", driver: "{{ DB_DRIVER }}", user: "{{ REG_DB_USER}}", pass: "{{ REG_DB_PASS }}" }
  become_user: "{{ user }}"
  when: 
    - PRODUCT_FLAG == "integrator"
    - PRODUCT_NAME != "msg-broker"

- name: Edit conf files
  template:
     src: "{{ role_path }}/templates/{{ PRODUCT_FLAG }}/{{ item.src }}"
     dest: "{{ PRODUCT_HOME }}/conf/{{ item.dest }}"
     mode: 0775
  with_items:
#    - { src: secret-conf.properties.j2, dest: secret-conf.properties }
    - { src: registry.xml.j2, dest: registry.xml }
    - { src: user-mgt.xml.j2, dest: user-mgt.xml }
    - { src: identity.xml.j2, dest: identity/identity.xml }
    - { src: axis2_nhttp.xml.j2, dest: axis2/axis2_nhttp.xml }
    - { src: axis2_pt.xml.j2, dest: axis2/axis2_pt.xml }
    - { src: axis2.xml.j2, dest: axis2/axis2.xml }
    - { src: axis2_client.xml.j2, dest: axis2/axis2_client.xml }
    - { src: carbon.xml.j2, dest: carbon.xml }
    - { src: catalina-server.xml.j2, dest: tomcat/catalina-server.xml }
    - { src: tomcat-users.xml.j2, dest: tomcat/tomcat-users.xml }
    - { src: data-agent-config.xml.j2, dest: data-bridge/data-agent-config.xml }
  become_user: "{{ user }}"
  when: 
    - PRODUCT_FLAG == "integrator"
    - PRODUCT_NAME != "msg-broker"

######################### INTEGRATOR: MSG-BROKER ##################################################

- name: Editing integrator.sh and setting access level
  template:
      src: "{{ role_path }}/templates/{{ PRODUCT_FLAG }}/{{ PRODUCT_NAME }}/integrator.sh.j2"
      dest: "{{ PRODUCT_HOME }}/bin/integrator.sh"
      mode: 0775
  become_user: "{{ user }}"
  when: PRODUCT_NAME == "msg-broker"

- name: Edit conf/datasources/master-datasources.xml
  template:
    src: "{{ role_path }}/templates/{{ PRODUCT_FLAG }}/{{ PRODUCT_NAME }}/master-datasources.xml.j2"
    dest: "{{ PRODUCT_HOME }}/wso2/broker/conf/datasources/master-datasources.xml"
    mode: 0775
  with_items:
    - { db_name: "{{ REG_DB_NAME }}", url: "{{ REG_DB_URL }}", driver: "{{ DB_DRIVER }}", user: "{{ REG_DB_USER}}", pass: "{{ REG_DB_PASS }}" }
  become_user: "{{ user }}"
  when: PRODUCT_NAME == "msg-broker"

- name: Edit conf files
  template:
     src: "{{ role_path }}/templates/{{ PRODUCT_FLAG }}/{{ PRODUCT_NAME }}/{{ item.src }}"
     dest: "{{ PRODUCT_HOME }}/wso2/broker/conf/{{ item.dest }}"
     mode: 0775
  with_items:
    - { src: registry.xml.j2, dest: registry.xml }
    - { src: user-mgt.xml.j2, dest: user-mgt.xml }
    - { src: identity.xml.j2, dest: identity/identity.xml }
    - { src: axis2_client.xml.j2, dest: axis2/axis2_client.xml }
    - { src: broker.xml.j2, dest: broker.xml }
    - { src: carbon.xml.j2, dest: carbon.xml }
    - { src: catalina-server.xml.j2, dest: tomcat/catalina-server.xml }
    - { src: tomcat-users.xml.j2, dest: tomcat/tomcat-users.xml }
  become_user: "{{ user }}"
  when: PRODUCT_NAME == "msg-broker"

###################################################################################################


