---
- hosts: localhost
  connection: local
  gather_facts: no 
  tasks:
  - ec2_ami:
        aws_access_key: AKIAJGMEXUDPLS4PF32A
        aws_secret_key: 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
        image_id: "{{ image_id }}" 
        delete_snapshot: True 
        state: absent
        ec2_url: https://ec2.eu-east-2.amazonaws.com
